spring:
  application:
    name: demo
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5432/spring-data-lab
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
     init:
      mode: always
server:
  port: 8080
